"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { dataProvider, type Insight } from "@/lib/data";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui-states";
import { ItemType } from "@/components/item-type";
const relative = (date:string) => Math.round((Date.now()-new Date(date).getTime())/3600000) < 24 ? `${Math.max(1,Math.round((Date.now()-new Date(date).getTime())/3600000))}h ago` : "Earlier";
export function InsightsPage() { const params=useSearchParams(); const [insights,setInsights]=useState<Insight[]>([]); const [active,setActive]=useState<Insight|null>(null); const [error,setError]=useState<string|null>(null); useEffect(()=>{void dataProvider.listInsights().then((list)=>{setInsights(list);setActive(list.find((i)=>i.id===params.get("insight"))??list[0]??null);}).catch(()=>setError("Insights could not be loaded."));},[params]); if(error)return <ErrorState message={error}/>; if(!active && insights.length===0)return <EmptyState title="No insights yet" detail="Insights will appear when evidence is available."/>; return <div className="min-h-[calc(100vh-3.5rem)] bg-white lg:flex"><section className="w-full border-b hairline lg:w-[380px] lg:shrink-0 lg:border-b-0 lg:border-r"><div className="border-b hairline p-5"><h1 className="font-semibold">Insights</h1></div><div className="divide-y divide-slate-100">{!insights.length?<LoadingState/>:insights.map((insight)=><button key={insight.id} onClick={()=>setActive(insight)} className={`focus-ring block w-full p-5 text-left ${active?.id===insight.id?"bg-[#eff4ff]":"hover:bg-slate-50"}`}><span className="flex justify-between text-xs text-slate-500"><span>{insight.evidence.length} sources</span><time className="mono text-[10px]">{relative(insight.createdAt)}</time></span><b className="mt-2 block leading-snug">{insight.title}</b><p className="mt-2 line-clamp-2 leading-relaxed text-slate-600">{insight.summary}</p></button>)}</div></section>{active&&<main className="flex-1"><div className="mx-auto max-w-3xl space-y-8 px-5 py-8 sm:px-10"><header className="space-y-3 border-b hairline pb-7"><h2 className="text-[28px] font-semibold tracking-[-.035em]">{active.title}</h2><p className="text-[15px] leading-relaxed text-slate-600">{active.explanation}</p></header><section><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">Evidence</h3><span className="mono text-[11px] text-slate-500">{active.evidence.length} references</span></div><div className="space-y-4">{active.evidence.map((evidence,index)=><article key={`${evidence.itemId}-${index}`} className="space-y-4 rounded border hairline p-5"><div className="flex items-center justify-between gap-3"><b>{evidence.sourceTitle}</b><span className="shrink-0"><ItemType type={evidence.sourceType}/></span></div><blockquote className="border-l-2 border-slate-300 pl-4 text-[15px] italic leading-relaxed">“{evidence.excerpt}”</blockquote><div className="flex justify-end"><Link href={`/vault?item=${evidence.itemId}`} className="focus-ring text-xs font-medium hover:underline">Open source →</Link></div></article>)}</div></section></div></main>}</div>; }
