"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Icon } from "./icons";
import { FolderIcon } from "@heroicons/react/24/outline";
const navigation = [{ href:"/dashboard" as const, label:"Dashboard", icon:"home" as const }, { href:"/vault" as const, label:"Vault", icon:"vault" as const }, { href:"/insights" as const, label:"Insights", icon:"insights" as const }];
export function AppShell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); const [open, setOpen] = useState(false); const page = navigation.find((n) => pathname.startsWith(n.href))?.label ?? "Flare"; const nav = <nav className="space-y-1" aria-label="Primary navigation">{navigation.map((item) => { const active = pathname.startsWith(item.href); return <Link onClick={() => setOpen(false)} className={`focus-ring flex items-center gap-2.5 rounded-md border-l-2 px-3 py-2 transition-colors ${active ? "border-slate-950 bg-[#eff4ff] font-medium text-slate-950" : "border-transparent text-slate-600 hover:bg-slate-50 hover:text-slate-950"}`} href={item.href} key={item.href}><Icon name={item.icon} className={`h-[18px] w-[18px] ${active ? "text-slate-950" : ""}`} />{item.label}</Link>; })}</nav>;
return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 z-40 hidden w-60 flex-col justify-between border-r hairline bg-white p-4 md:flex"><div className="space-y-7"><Link href="/dashboard" className="flex items-center gap-2 px-1"><span className="flex h-7 w-7 items-center justify-center rounded-[4px] bg-black text-white">♨</span><span><b className="block text-[18px] tracking-tight">Flare</b><span className="mono block text-[10px] tracking-[.13em] text-slate-500">AI SECOND BRAIN</span></span></Link>{nav}</div><div className="border-t hairline pt-3 text-slate-600"><div className="flex items-center gap-2 px-3 py-2"><FolderIcon className="h-[18px] w-[18px]"/>Acme Corp / Founder</div><div className="flex cursor-not-allowed items-center gap-2 px-3 py-2 opacity-60"><Icon name="settings" className="h-[18px] w-[18px]"/>Settings</div></div></aside>
<header className="fixed inset-x-0 top-0 z-30 flex h-14 items-center justify-between border-b hairline bg-white px-4 md:left-60 md:px-5"><div className="flex items-center gap-3"><button onClick={() => setOpen(true)} className="focus-ring rounded p-1 md:hidden" aria-label="Open navigation"><Icon name="menu" className="h-5 w-5"/></button><span className="text-slate-500">Flare</span><span className="text-slate-400">/</span><span className="font-medium">{page}</span></div><div className="flex items-center gap-3"><Link href="/dashboard" className="focus-ring hidden items-center gap-1.5 rounded bg-slate-950 px-3 py-1.5 text-xs font-medium text-white sm:flex"><Icon name="plus" className="h-4 w-4"/>New item</Link><span className="mono flex h-7 w-7 items-center justify-center rounded-full border border-slate-300 bg-[#e5eeff] text-[10px]">FD</span></div></header>
{open && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="Close navigation" onClick={() => setOpen(false)} className="absolute inset-0 bg-slate-950/20"/><aside className="relative flex h-full w-72 flex-col justify-between border-r hairline bg-white p-4 shadow-xl"><div className="space-y-7"><div className="flex items-center justify-between"><b className="text-lg">Flare</b><button onClick={() => setOpen(false)} className="focus-ring rounded p-1"><Icon name="close" className="h-5 w-5"/></button></div>{nav}</div><div className="border-t hairline pt-3 text-slate-600">Acme Corp / Founder</div></aside></div>}
<main className="pt-14 md:pl-60">{children}</main></div>; }
